---
- name: add php repository
  apt_repository: repo='ppa:ondrej/php5-5.6' state=present

- name: install php
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: "{{php56_modules}}"

- name: configure php cli
  template: src=php/cli.tpl dest=/etc/php5/cli/conf.d/00-provision.ini