---
- name: add php repository
  apt_repository: repo='ppa:ondrej/php5-5.6' state=present

- name: enable php
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: "{{php56_modules_enabled}}"

- name: disable php modules
  apt: pkg={{item}} state=absent
  with_items: "{{php56_modules_disabled}}"

- name: configure php cli timezone
  template: src=php/cli.tpl dest=/etc/php5/cli/conf.d/00-provision-timezone.ini