---
- name: include os variables
  include_vars: "{{php56_os}}.yml"
  when: php56_os is defined and php56_os != ""

################################################################################################

# define os variables

- name: define php56_modules
  set_fact:
    php56_modules: "{{__php56_modules}}"
  when: php56_modules is not defined

- name: define php56_modules_optional
  set_fact:
    php56_modules_optional: "{{__php56_modules_optional}}"
  when: php56_modules_optional is not defined

- name: define php56_apache2_modules
  set_fact:
    php56_apache2_modules: "{{__php56_apache2_modules}}"
  when: php56_apache2_modules is not defined

- name: define php56_apache2_modules_optional
  set_fact:
    php56_apache2_modules_optional: "{{__php56_apache2_modules_optional}}"
  when: php56_apache2_modules_optional is not defined

- name: define php56_command_webserver_restart
  set_fact:
    php56_command_webserver_restart: "{{__php56_command_webserver_restart}}"
  when: php56_command_webserver_restart is not defined

################################################################################################

# setup os

- name: setup {{php56_os}}
  include: "{{php56_os}}.yml"
  when: php56_os is defined and php56_os != ""

- name: setup webserver-apache2
  include: "webserver-apache2.yml"
  when: php56_os is defined and php56_os != "" and php56_webserver_enabled == true and php56_webserver_type == "apache2"