---
- name: install main php56 packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    # meta-package, automatically installs:
    # apache2 apache2-bin apache2-data libapache2-mod-php5 libapr1 libaprutil1
    # libaprutil1-dbd-sqlite3 libaprutil1-ldap php5-cli php5-common php5-json
    # php5-readline ssl-cert
    - php5

- name: enable apache2 php56 module
  apache2_module: state=present name=php5
  notify: php56_webserver_restart

- name: enable optional apache2 modules
  apache2_module: state=present name={{item}}
  with_items: "{{php56_apache2_modules_enabled}}"
  notify: php56_webserver_restart

- name: disable optional apache2 modules
  apache2_module: state=absent name={{item}}
  with_items: "{{php56_apache2_modules_disabled}}"
  notify: php56_webserver_restart

- name: configure php56 apache2
  template: src={{server_base_os}}/etc/php5/apache2/conf.d/00-provision.ini.tpl dest=/etc/php5/apache2/conf.d/00-provision.ini
  notify: php56_webserver_restart

# remove apache2 default vhost

- name: disable apache2 default
  include: ubuntu14-webserver-apache2-vhost-disable.yml vhost=000-default

# handle vhost default

- name: enable vhost default
  include: ubuntu14-webserver-apache2-vhost-enable.yml vhost=000-vhost-default
  when: php56_webserver_vhost_default_enabled == true

- name: disable vhost default
  include: ubuntu14-webserver-apache2-vhost-disable.yml vhost=000-vhost-default
  when: php56_webserver_vhost_default_enabled != true

# handle vhost builds

- name: enable vhost builds
  include: ubuntu14-webserver-apache2-vhost-enable.yml vhost=001-vhost-builds
  when: php56_webserver_vhost_builds_enabled == true

- name: disable vhost builds
  include: ubuntu14-webserver-apache2-vhost-disable.yml vhost=001-vhost-builds
  when: php56_webserver_vhost_builds_enabled != true

# handle vhost releases

- name: enable vhost releases
  include: ubuntu14-webserver-apache2-vhost-enable.yml vhost=002-vhost-releases
  when: php56_webserver_vhost_releases_enabled == true

- name: disable vhost builds
  include: ubuntu14-webserver-apache2-vhost-disable.yml vhost=002-vhost-releases
  when: php56_webserver_vhost_releases_enabled != true

# handle vhost dynamic

- name: enable vhost dynamic
  include: ubuntu14-webserver-apache2-vhost-enable.yml vhost=1000-vhost-dynamic
  when: php56_webserver_vhost_dynamic_enabled == true

- name: disable vhost dynamic
  include: ubuntu14-webserver-apache2-vhost-disable.yml vhost=1000-vhost-dynamic
  when: php56_webserver_vhost_dynamic_enabled != true